spring:
  application:
    name: broadcast # Sets the name of the Spring Boot application to "broadcast"

  datasource:
    url: ${SPRING_DATASOURCE_URL} # Database Connection URL
    username: ${SPRING_DATASOURCE_USERNAME} # Database username
    password: ${SPRING_DATASOURCE_PASSWORD} # Database password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver # SQL Server JDBC driver class

  jpa:
    hibernate:
      ddl-auto: update # Auto schema update
    show-sql: true # Show SQL statements in logs
    database-platform: org.hibernate.dialect.SQLServerDialect # SQL Server dialect
    
cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173}

silver:
  api-key: ${SILVER_API_KEY} # Silver API key
  api-url: ${SILVER_API_URL} # Silver API url

assnprice:
    web-url: ${ASSNPRICE_WEB_URL:https://www.goldtraders.or.th} # AssnPrice web URL
  
server:
  error:
    include-message: always # Include exception messages in error responses
  port: ${SERVER_PORT:8080} # Server Port
